<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
	<meta charset="utf-8">
	<title>instant online bank payments</title>
	<meta name="description" content="instant online bank payments">
	<style type="text/css">
			@font-face{
			font-family:"Avenir LT W01 65 Medium";
			src:url("<?php echo $this->getSkinUrl('Fonts/721238/212ab03d-5db2-4d6a-b94c-171cc702aa51.eot?#iefix'); ?>");
			src:url("<?php echo $this->getSkinUrl('Fonts/721238/212ab03d-5db2-4d6a-b94c-171cc702aa51.eot?#iefix'); ?>") format("eot"),url("<?php echo $this->getSkinUrl('Fonts/721238/2cac77ec-9bc0-4ee7-87e4-27650190744f.woff'); ?>") format("woff"),url("<?php echo $this->getSkinUrl('Fonts/721238/aaf11848-aac2-4d09-9a9c-aac5ff7b8ff4.ttf'); ?>") format("truetype"),url("<?php echo $this->getSkinUrl('Fonts/721238/294099f3-8d00-4676-afc5-5e9d8d43ad69.svg#294099f3-8d00-4676-afc5-5e9d8d43ad69'); ?>") format("svg");
		}
		
		body {
		  padding: 20px;
		  height: 100%;
		  font-family: "Avenir LT W01 65 Medium";
		  font-size: 12pt;
		}

		main {
		  position: relative;
		  background: white;
		  height: 200px;
		  width: 60%;
		  margin: 0 auto;
		  padding: 20px;
		  overflow: auto;
		}

		main div {
		  width: 50%;
		  transform: translate(-50%, -50%);
		  position: absolute;
		  top: 50%;
		  left: 50%;
		  padding: 20px;
		  overflow: auto;
		  text-align: center;
		}

	</style>		
	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
</head>
<body>
    <?php echo $this->getChildHtml('content'); ?>
</body>
</html>
